-- Q1 What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer1
GROUP BY gender;


-- Q2 Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount_usd
FROM customer1
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (
    SELECT AVG(purchase_amount_usd)
    FROM customer1
);


-- Q3 Which are the top 5 products with the highest average review ratings?

SELECT item_purchased,
ROUND(AVG(review_rating), 2) AS avg_product_ratings
FROM customer1
GROUP BY item_purchased
ORDER BY avg_product_ratings DESC
LIMIT 5;


-- Q4 Compare the average purchase amounts between standard and express shipping.

SELECT shipping_type,
ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase
FROM customer1
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5 Do customers with subscription spend more money than those without subscription?

SELECT subscription_status,
ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer1
GROUP BY subscription_status;


-- Q6 Are subscribed customers more valuable than non-subscribed customers?

SELECT item_purchased,
ROUND(
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
    / COUNT(*), 2
) AS discount_percentage
FROM customer1
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7 Customers who buy many times (more than 5 purchases)

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer1
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q8 What is the revenue contribution of each age group

SELECT age_group,
SUM(purchase_amount_usd) AS total_revenue
FROM customer1
GROUP BY age_group
ORDER BY total_revenue DESC;